<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <IsPackable>False</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="9.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EventFlow\EventFlow.csproj" />
  </ItemGroup>
</Project>
