# Please note, some of the services can be installed on your machine 

version: '2.4'

services:

  rabbitmq:
    image: rabbitmq:4.0.2-management-alpine
    container_name: rabbitmq-ef
    ports:
      - "5672:5672"
      - "15672:15672"

  eventstore:
    image: eventstore/eventstore:24.6
    container_name: eventstore-ef
    environment:
      - EVENTSTORE_INSECURE=true
    ports:
      - "1113:1113"
      - "2113:2113"

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password12!
    ports:
      - "5432:5432"
